### ISSUE TITLE
upgrade-hass.sh suggestion

### ISSUE THREAD

**Issue by rubasace** [mf-social/Home-Assistant#595]
I think this block over here takes too much time to execute, because it´s always destroying everything and recreating it back:

`
docker-compose down
docker-compose pull
docker-compose up -d`

My understanding is that that´s done with the intention of removing any container that might have been removed from the docker-compose.yaml file. 
If that´s the case, you can simply use ` docker-compose up -d --remove-orphans ` as it´s clear advantage is that it won´t recreate all the already up to date containers. Feel free to have a look at my script as it´s been inspired by yours:

`#!/bin/bash

START_TIME=$SECONDS

cd $USERDIR/docker
git fetch origin master
git reset --hard origin/master
docker-compose up -d --remove-orphans
#TODO only when homeassistant says that is up to date (homeassistant is up-to-date)
docker-compose restart homeassistant
docker system prune -fa
docker volume prune -f

ELAPSED_TIME=$(($SECONDS - $START_TIME))

echo "Total duration: ${ELAPSED_TIME}s"

exit`

Please let me know if I´m missing something as it may be the case.

**Comment by mf-social** [comment]
Hi, thanks for the comments :)

I'm still learning about how docker compose works, and I was kinda thinking about it as 

1 - shut down everything 
2 - update everything 
3 - restart everything in the correct order

The idea of this script is to be run headless from within home assistant, like press a button and update everything, or automatically at 3am every Wednesday or whatever.

Will it update everything with your method, with no `docker-compose pull` command?

**Comment by rubasace** [comment]
See? I always miss something :D 

As far as I know it won´t update your docker images if a newer is available, but will apply all the changes you write to your docker-compose.yaml file, of course.
It depends on your priorities, I´m software engineer and I feel this need of maximizing the up times for everything so I rather prefer having the update of the images as part of a different process.

I recommend you to have a look at this 2 links:

[Basic setup of a media server with docker-compose](https://www.smarthomebeginner.com/docker-home-media-server-2018-basic/)
[Use reverse proxy to expose services on a domain, https, etc](https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/)

In the first one have an special look to watchtower, cause it takes care of your images for you: you specify how often you want, and it does the update of the containers to the latest version.
The good thing about the second one is that youu don´t depend on exposing ports on your router and that kind of things, also gives you https certificates, etc (even though I wouldn´t expose home assistant to the internet)

And just to finish, have a look at [my docker-compose-yaml](https://github.com/rubasace/home-assistant/blob/master/docker-compose.yml)  if you want. As you see everything is exposed on subdomains under my main domain, at exception of home assistant, that is only accessible through the port inside the same networ

Hope it helps :)

PS: I´m starting with home assistant, so don´t take anything else in that repo as a guidance :P

**Comment by mf-social** [comment]
I'm using organizr which has a built-in ngnix reverse proxy, and I prefer to click the 'upgrade' button when I'm ready to deal with any breaking changes rather than use something like watchtower which would do it 'unsupervised'.

I can't see anywhere in that guide where it says you can get remote access without port forwarding. In fact it specifically says you need to forward 443 and 80 which is the same as my setup?? 

I get where you're coming from re 'uptime', but this doesn't really apply to a homeassistant setup in the same way I don't think.

It's up all the time, except when I am working on it or upgrading it, so a few seconds to restart here and there is expected behaviour.

**Comment by mf-social** [comment]
**ugh, pressed the wrong button**

**Comment by rubasace** [comment]
The thing with organizr is that it's using the external ips to show you the services, so you are entering your server through the organizr entry point (ports 80 and 443), but then organizr is connecting to your containers through their own ports, that I guess are also opened in your router, so mainly is just an organizer of external endpoints. At least that was my experience when I firstly setup my other NAS with it. With traefik you only expose traefik in both 80 and 443 and it redirects internally given the rules, so you only need to open the ports in your router for 80 and 443, but not for the rest of the services. Please correct me if I'm wrong at this point and you are only exposing 80 and 443 too.

> I can't see anywhere in that guide where it says you can get remote access without port forwarding. In fact it specifically says you need to forward 443 and 80 which is the same as my setup??

They say this in the traefik one:

> You do not have to expose or forward ports on your router. Exposing ports to the internet can be security risk if the app is not sufficiently protected or has a security flaw.

On top of that, traefik will handle your https certificates totally automatically, so you'll have all your traffic through https effortless (even redirecting automatically if you hit on your http endpoint). It will also allow you to secure certain endpoints with credentials even if the service itself doesn't give you that option.

> I prefer to click the 'upgrade' button when I'm ready to deal with any breaking changes rather than use something like watchtower which would do it 'unsupervised'.

I totally get your point on this one, I felt the same way the first time I read about watchtower. Truth though is that I've been running it for 1 year aprox, with 22 different containers and I only have had one issue so far (one of the services changed the name of one of the files for configuration and it broke). The thing is that image updates are backwards compatible 99.9% of the time, but again, I see why you'd prefer to have it done only when you are ready to fix it :)

**Comment by mf-social** [comment]
I only have 80 and 443 forwarded, and all of my traffic is redirected via https. 

The very first paragraph of that guide, 'requirements' says:

```
1 - Home Server – While guide is based on Ubuntu, setting up Traefik reverse proxy for Docker should work any Linux OS
2 - Docker Media Server – You should already have a Docker media server setup. If you are a newbie, I strongly recommend reading my basic guide as we will be pulling certain parts from there.
3 - Port Forwarding – Traefik Reverse Proxy uses ports 80 and 443. These ports must be forwarded on your router to the server with Traefik docker instance.
```

So it doesn't make sense that it later says you don't have to.

As for the watchtower bit, I think it makes sense if your stack *isn't* centred around homeassistant, but mine is and it's basically beta software that is updated several times a week with multiple breaking changes in each update, so I think it needs more supervision for updates.

Once it's 'stable' I would definitely use an automated system, but for now the manual touch is definitely the least stressful option :)

**Comment by rubasace** [comment]
I see, when I configured organizr, I wasn't able to use nginx as reverse proxy, just as a normal one, so I still needed all the ports exposed if I wanted to conect to the services _from outside my network_. 

> So it doesn't make sense that it later says you don't have to.

You have to do it only for traefik (80 and 443), not for every other service, but yes, it's not properly phrased in the article :D.

> Once it's 'stable' I would definitely use an automated system, but for now the manual touch is definitely the least stressful option :)

Sounds cool! 

Feel free to close the issue if you want, I'll keep an eye on your work, as I'm learning a lot from it.

**Comment by mf-social** [comment]
No worries 👍

Glad you're getting some benefit from the repo, it's a continuous work in progress, but it keeps me busy and I'm glad so many people have found some inspiration from it. 

Hopefully I'll get the wiki up over the weekend and you can see a bit more of how I've set up organizr and things and how it all comes together 🙂
